apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: 904484189421.dkr.ecr.us-east-1.amazonaws.com/test1:34fb18e9330786c59000b84953aec99e87aad4e8
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST 
          value: "terraform-2024061210501227910000000d.cjce0c82yelw.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "bqCore"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "CORE_ADMIN"
        - name: JWT_SECRET
          value: "hello_beeQuant"
      - name: test-container
        image: postgres:latest
        env:
        - name: DB_HOST
          value: "terraform-2024061210501227910000000d.cjce0c82yelw.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "bqCore"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "CORE_ADMIN"
        command: ["sh", "-c", "pg_isready -h $DB_HOST -p $DB_PORT -d $DB_NAME -U $DB_USERNAME"]
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp
